name = "adress_book"
description = ""
version = "0.1.0-dev"

authors = ["Milly"]
maintainers = ["Milly <example@example.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["adress_book"]
